version: "2"
# plugins:
#     eslint:
#         enabled: true
#         config: .eslintrc
ratings:
    paths:
        - "**.ts"
checks:
    file-lines:
        config:
            threshold: 250
    method-lines:
        config:
            threshold: 125
    complex-logic:
        config:
            threshold: 15
    method-complexity:
        config:
            threshold: 15
    similar-code:
        enabled: false
    identical-code:
        enabled: false
